services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  middleware:
    build: ./middleware
    ports:
      - "5000:5000"
    depends_on:
      - user
      - product

  user:
    build: ./services/user
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=banks
      - POSTGRES_DB=stock
      - POSTGRES_PORT=5432

  product:
    build: ./services/product
    ports:
      - "5002:5002"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=banks
      - POSTGRES_DB=stock
      - POSTGRES_PORT=5432

volumes:
  pg_data:
