global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'middleware'
    metrics_path: /metrics
    static_configs:
      - targets: ['middleware:5000']

  - job_name: 'user'
    metrics_path: /metrics
    static_configs:
      - targets: ['user:5001']

  - job_name: 'product'
    metrics_path: /metrics
    static_configs:
      - targets: ['product:5002']
  
  - job_name: 'app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:5003']
